name: SAGEnet
channels:
  - bioconda
  - r
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - mkl==2024.0
  - python=3.10
  - mamba
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pytorch-cuda=11.7
  - ca-certificates
  - certifi
  - openssl
  - ipykernel
  - pandas
  - matplotlib
  - lightning
  - nbconvert
  - tensorboard
  - seaborn
  - scipy
  - matplotlib-venn
  - pysam
  - tensorflow-hub
  - pip
  - pip:
      - tangermeme